#
# https://docs.docker.com/engine/installation/linux/fedora/\
# http://developers.redhat.com/blog/2014/05/15/practical-introduction-to-docker-containers/
#

#
# System
# 
# systemctl start docker
# systemctl enable docker.service
# systemctl start docker.service

# sudo service docker start
# docker daemon
# sudo docker info


#
# Controlling containers
# docker --help
# docker ps  -a -> list running and sleeping docker
# sudo docker run -it centos:6 -> start the image
# Ctrl -p  Ctrl -q -> detach the docker
# docker attach e3a3651e9b58 -> attach, address from docker ps
# Start a new container
$ JOB=$(docker run -d ubuntu /bin/sh -c "while true; do echo Hello world; sleep 1; done")
# Stop the container
$ docker stop $JOB
# Start the container
$ docker start $JOB
# Restart the container
$ docker restart $JOB
# SIGKILL a container
$ docker kill $JOB
# Remove a container
$ docker stop $JOB # Container must be stopped to remove it
$ docker rm $JOB
 
 
 
#
# mounting external disk
# we need to mount R drives and the local image of the neuro-image software (FSL, SPM, ANTs)
# centralized the software in 

mkdir /mnt/neuroimaging/

#docker build -f Dockerfile --tag="ucsfmac/gateway:$1" .
#docker tag -f ucsfmac/gateway:$1 ucsfmac/gateway:latest

docker build -f Dockerfile --tag="ucsfmac/gateway:01" .
docker tag -f ucsfmac/gateway:01 ucsfmac/gateway:latest




  docker run -d  --name gw_mac1  -h gw-1.mac-internal.net --net=none --cap-add=NET_ADMIN --dns 10.36.0.8 --dns 10.36.0.9  -v /containers/gw_mac1/conf/:/opt/conf/ -v /containers/gw_mac1/service/:/etc/service/  ucsfmac/gateway:latest
  
  docker run -d  --name Neuro   --cap-add=NET_ADMIN --dns 10.36.56.196  -v /containers/Neuro/mnt/neuroimaging:/mnt/neuroimaging/  ucsfmac/gateway:latest
  
