#
# https://docs.docker.com/engine/installation/linux/fedora/\
# http://developers.redhat.com/blog/2014/05/15/practical-introduction-to-docker-containers/
#

#
# System
# 
# systemctl start docker
# systemctl enable docker.service
# systemctl start docker.service

# sudo service docker start
# docker daemon
# sudo docker info


#
# Controlling containers
# docker --help
# docker ps  -a -> list running and sleeping docker
# sudo docker run -it centos -> start the image
# Ctrl -p  Ctrl -q -> detach the docker
# docker attach e3a3651e9b58 -> attach, address from docker ps
# Start a new container
$ JOB=$(docker run -d ubuntu /bin/sh -c "while true; do echo Hello world; sleep 1; done")
# Stop the container
$ docker stop $JOB
# Start the container
$ docker start $JOB
# Restart the container
$ docker restart $JOB
# SIGKILL a container
$ docker kill $JOB
# Remove a container
$ docker stop $JOB # Container must be stopped to remove it
$ docker rm $JOB
 
